#%RAML 0.8
---
title: Sybil
baseUri: https://api.sybil.synyx.coffee
version: v1
mediaType: application/vnd.synyx.sybil-v1+hal+json

documentation:
 - title: Introduction
   content: |
    This API maps Inputs to Outputs.  
    **Inputs** can bei either *status*es, from Jenkins builds or systems watched by Nagios, or *binary*s, e.g. buttons &
    switches, either on a web-interface or actual physical objects.  
    **Outputs** can be either *light*s (white light, illuminating the room at large) or *ledstrip*s (multi-colored
    lights, used mostly for information).
    
    Each Input can control zero or more Outputs, and each Output can be controlled by zero or more Inputs.  
    Accordingly, each Input has a list of associated Outputs and each Output a list of associated Inputs.

    
 - title: Media Types
   content: |
    Responses will usually contain a body of the type
    
        application/vnd.synyx.sybil-v1+hal+json
        
    or, in some cases, no body at all.
    
    Request should have the type
    
        application/vnd.synyx.sybil-v1+json
        
    In case of an error, the body of the response will be of the type
    
        application/problem+json
 
 - title: Missing examples
   content: Examples for the HTTP **HEAD** and **OPTIONS** verbs are not provided, as these are subsets of the **GET**
    verb.
 
 - title: Unsupported methods
   content: |
    Using an unsupported verb on a ressource will result in this error message:

    > #### HTTP status code [405](http://httpstatus.es/405)
    > ---
    > Error - METHOD NOT ALLOWED
    >
    > Body
    >
    > **Type: application/problem+json**
    >
    > **Example:**
    >
    >     {
    >       "type": "http://sybil.synyx.coffee/errors/method_not_allowed",
    >       "title": "Method Not Allowed",
    >       "detail": "This resource does not support PUT"
    >     }
        

traits:
  - paginated:
      queryParameters:
        offset:
          type: number
          description: The first entry to be retrieved
          required: false
          example: offset=20
        limit:
          type: number
          description: The number of entries that will be retrieved
          required: false
          example: limit=10

/:
  description: API root
  get:
    description: Retrieve the API root.
    responses:
      200:
        description: Success - OK
        headers:
          Allow:
            example: GET
        body:
          example: !include root-get.example

/inputs:
  description: Inputs, controlling outputs.
  get:
    description: |
      Retrieve the list of inputs.   
      **Note:** This returns only truncated input objects.
    is: [ paginated ]
    queryParameters:
      type:
        type: string
        description: The type of the Input
        required: false
        example: type=status
    responses:
      200:
        description: Success - OK
        headers:
          Allow:
            example: GET
        body:
          example: !include inputs-get.example      
  
  /{inputname}:
    description: A specific input
    get:
      description: Retrieve a specific input.
      responses:
        200:
          description: Success - OK
          headers:
            Allow:
              example: GET, PUT, DELETE
          body:
            example: !include input-get.example
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include input-not-found.example
    put:
      description: Create or update an input.
      body:
        application/vnd.synyx.sybil-v1+json:
          schema: !include input.schema
          example: !include input-put.example
      responses:
        200:
          description: |
            Success - OK
            
            **Example:** See below.
        201:
          description: Success - CREATED
          body:
            example: !include input-get.example
        400:
          description: Error - BAD REQUEST
          body:
            application/problem+json:
              example: !include input-put-validation-error.example
    delete:
      description: Delete an input.
      responses:
        204:
          description: Success - NO CONTENT
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include input-not-found.example

    /state:
      description: | 
       *Singleton:* The input's state
      get:
        description: Retrieve the input's state
        responses:
          200:
            description: Success - OK
            headers:
              Allow:
                example: GET, PUT
            body:
              example: !include input-state-get.example
      put:
        description: Update the input's state
        body:
          application/vnd.synyx.sybil-v1+json:
            schema: !include input-state.schema
            example: !include input-state-put.example
        responses:
          200:
            description: Success - OK
            body:
              example: !include input-state-get.example
          400:
            description: Error - BAD REQUEST
            body:
              application/problem+json:
                example: !include input-state-validation-error.example
        
    /outputs:
      description: Links to the outputs this input is controlling.
      get:
        description: Retrieve the list of this input's associated outputs.
        is: [ paginated ]
        queryParameters:
          type:
            type: string
            description: The type of the Output
            required: false
            example: type=light
        responses:
          200:
            description: Success - OK
            headers:
              Allow:
                example: GET, POST
            body:
              example: !include input-outputs-get.example
  
      /{outputname}:
        description: A specific associated output.
        get:
          description: Retrieve a specific associated output.
          responses:
            200:
              description: Success - OK
              headers:
                Allow:
                  example: GET, PUT, DELETE
              body:
                example: !include input-outputs-output-get.example
            404:
              description: Error - NOT FOUND
              body:
                application/problem+json:
                  example: !include output-not-found.example
        put:
          description: Associate a new output with this input.
          responses:
            201:
              description: Success - CREATED
              body:
                example: !include input-outputs-output-get.example
            404:
              description: Error - NOT FOUND
              body:
                application/problem+json:
                  example: !include inputs-input-output-not-found.example
        delete:
          description: Remove the input's association with this output.
          responses:
            204:
              description: Success - NO CONTENT
            404:
              description: Error - NOT FOUND
              body:
                application/problem+json:
                  example: !include output-not-found.example

/outputs:
  description: Outputs.
  get:
    description: |
      Retrieve the list of outputs.   
      **Note:** This returns only truncated output objects.
    is: [ paginated ]
    queryParameters:
      type:
        type: string
        description: The type of the Output
        required: false
        example: type=ledstrip
    responses:
      200:
        description: Success - OK
        headers:
          Allow:
            example: GET
        body:
          example: !include outputs-get.example      
  
  /{outputname}:
    description: A specific output
    get:
      description: Retrieve a specific output.
      responses:
        200:
          description: Success - OK
          headers:
            Allow:
              example: GET, PUT, DELETE
          body:
            example: !include output-get.example
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include output-not-found.example
    put:
      description: Create or update an output.
      body:
        application/vnd.synyx.sybil-v1+json:
          schema: !include output.schema
          example: !include output-put.example
      responses:
        200:
          description: |
            Success - OK
            
            **Example:** See below.
        201:
          description: Success - CREATED
          body:
            example: !include output-get.example
        400:
          description: Error - BAD REQUEST
          body:
            application/problem+json:
              example: !include outputs-post-validation-error.example
    delete:
      description: Delete an output.
      responses:
        204:
          description: Success - NO CONTENT
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include output-not-found.example
  
    /inputs:
      description: Links to the inputs this output is controlled by. 
      get:
        description: Retrieve the list of the output's associated inputs.
        is: [ paginated ]
        queryParameters:
          type:
            type: string
            description: The type of the Input
            required: false
            example: type=binary
        responses:
          200:
            description: Success - OK
            headers:
              Allow:
                example: GET
            body:
              example: !include output-inputs-get.example
  
      /{inputname}:
        description: A specific associated input.
        get:
          description: Retrieve a specific associated input.
          responses:
            200:
              description: Success - OK
              headers:
                Allow:
                  example: GET, PUT, DELETE
              body:
                example: !include output-inputs-input-get.example
            404:
              description: Error - NOT FOUND
              body:
                application/problem+json:
                  example: !include input-not-found.example
        put:
          description: Associate a new input with this output.
          responses:
            201:
              description: Success - CREATED
              body:
                example: !include output-inputs-input-get.example
            400:
              description: Error - BAD REQUEST
              body:
                application/problem+json:
                  example: !include outputs-output-input-not-found.example        

        delete:
          description: Remove the output's association with this input.
          responses:
            204:
              description: Success - NO CONTENT
            404:
              description: Error - NOT FOUND
              body:
                application/problem+json:
                  example: !include input-not-found.example
