#%RAML 0.8
---
title: Sybil
baseUri: https://api.sybil.synyx.coffee
version: v1
mediaType: application/vnd.synyx.sybil-v1+hal+json

traits:
  - paginated:
      queryParameters:
        offset:
          type: number
          description: The first entry to be retrieved
          required: false
          example: offset=20
        limit:
          type: number
          description: The number of entries that will be retrieved
          required: false
          example: limit=10

/:
  description: API root
  get:
    description: Retrieve the API root.
    responses:
      200:
        description: Success - OK
        headers:
          Allow:
            example: GET
        body:
          example: !include root-get.example

/inputs:
  description: Inputs, controlling outputs.
  get:
    description: |
      Retrieve the list of inputs.   
      **Note:** This returns only truncated input objects.
    is: [ paginated ]
    queryParameters:
      type:
        type: string
        description: The type of the Input
        required: false
        example: type=status
    responses:
      200:
        description: Success - OK
        headers:
          Allow:
            example: GET, POST
        body:
          example: !include inputs-get.example      
  post:
    description: Create a new input.
    body:
      application/vnd.synyx.sybil-v1+json:
        schema: !include inputs-post-request.schema
        example: !include inputs-post-request.example
    responses:
      201:
        description: Success - CREATED
        headers:
          Location:
            example: /inputs/jenkins_sybil_web_ui
        body:
          example: !include input-get.example
      400:
        description: Error - BAD REQUEST
        body:
          application/problem+json:
            example: !include inputs-post-validation-error.example
  
  /{inputname}:
    description: A specific input
    get:
      description: Retrieve a specific input.
      responses:
        200:
          description: Success - OK
          headers:
            Allow:
              example: GET, PUT, PATCH, DELETE
          body:
            example: !include input-get.example
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include input-not-found.example
    put:
      description: Wholly update an input.
      body:
        application/vnd.synyx.sybil-v1+json:
          schema: !include input.schema
          example: !include input-put.example
      responses:
        200:
          description: Success - OK
          body:
            example: !include input-get.example
        400:
          description: Error - BAD REQUEST
          body:
            application/problem+json:
              example: !include input-patch-validation-error.example
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include input-not-found.example
    patch:
      description: Partially update an input.
      body:
        application/vnd.synyx.sybil-v1+json:
          schema: !include input-patch.schema
          example: !include input-patch-request.example
      responses:
        200:
          description: Success - OK
          body:
            example: !include input-patch-response.example
        400:
          description: Error - BAD REQUEST
          body:
            application/problem+json:
              example: !include input-patch-validation-error.example
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include input-not-found.example
    delete:
      description: Delete an input.
      responses:
        204:
          description: Success - NO CONTENT
        404:
          description: Error - NOT FOUND
          body:
            application/problem+json:
              example: !include input-not-found.example
        
    /outputs:
      description: The outputs this input is controlling.
      get:
        description: Retrieve the list of this input's associated outputs.
        is: [ paginated ]
        queryParameters:
          type:
            type: string
            description: The type of the Output
            required: false
            example: type=light
        responses:
          200:
            description: Success - OK
            headers:
              Allow:
                example: GET, POST
            body:
              example: !include input-outputs-get.example
      post:
        description: Associate a new output with this input.
        body:
          application/vnd.synyx.sybil-v1+json:
            schema: !include input-outputs.schema
            example: !include input-outputs-post-request.example
        responses:
          201:
            description: Success - CREATED
            headers:
              Location:
                example: /inputs/hauptschalter/outputs/saeule_admins
            body:
              example: !include input-outputs-output-get.example
          400:
            description: Error - BAD REQUEST
            body:
              application/problem+json:
                example: !include input-outputs-validation-error.example
  
      /{outputname}:
        get:
          description: Retrieve a specific associated output.
          responses:
            200:
              description: Success - OK
              headers:
                Allow:
                  example: GET, DELETE
              body:
                example: !include input-outputs-output-get.example
            404:
              description: Error - NOT FOUND
              body:
                application/problem+json:
                  example: !include output-not-found.example
        delete:
          description: Remove the input's association with this output.
          responses:
            204:
              description: Success - NO CONTENT
            404:
              description: Error - NOT FOUND
              body:
                application/problem+json:
                  example: !include output-not-found.example

/outputs:
  get:
    description: |
      Retrieve the list of outputs.   
      **Note:** This returns only truncated output objects.
    is: [ paginated ]
    queryParameters:
      type:
        type: string
        description: The type of the Output
        required: false
        example: type=ledstrip
    responses:
      200:
        description: Success - OK
        body:
          example: !include outputs-get.example      
  post:
  
  /{outputname}:
    get:
    put:
    patch:
    delete:
  
    /inputs:
      get:
        is: [ paginated ]
        queryParameters:
          type:
            type: string
            description: The type of the Input
            required: false
            example: type=binary
      post:
  
      /{inputname}:
        get:
        delete: