#!/bin/sh
if [ $# -lt 1 ] || [ "$1" = "--help" ]
    then
    echo "Usage: $0 URL [ARGS]"
    echo "  URL: URL to get from"
    echo " ARGS: form-encoded arguments (param1=value1&param2=value2&...)"
    exit
fi
if [ $# -gt 1 ]
    then
    PARAMETERS="?$2"
fi
curl -is $1$PARAMETERS
