#!/bin/sh
if [ $# -lt 2 ] || [ "$1" = "--help" ]
    then
    echo "Usage: $0 url data"
    echo "  url: URL to put to"
    echo " data: form-encoded data (param1=value1&param2=value2&...)"
    exit
fi
curl -is -X PUT --data $2 $1