#!/bin/sh
if [ $# -lt 2 ]
    then
    echo "Usage: $0 url data"
    echo "  url: URL to put"
    echo "  data: form-encoded data (param1=value1&param2=value2&...)"
    exit
fi
curl -v -X PUT --data $2 $1