#!/bin/sh

#CONFIG
DEFAULT_URL="http://httpbin.org/put "
COMMAND="./put"

if [ "$1" = "--help" ] #show help and exit
    then
    echo "Usage: $0 [OPTION] STATUS [URL]"
    echo "  OPTION:"
    echo "      -v: verbose"
    echo "      -q: quiet"
    echo "  STATUS: either 0 (OKAY), 1 (WARNING) or 2 (CRITICAL)"
    echo "     URL: URL to send status to; defaults to $DEFAULT_URL"
    exit
elif [ "$1" = "-q" ] #quiet mode
    then
    QUIET=true
    shift
    if [ "$1" = "-v" ] #can't be both, so we ignore it
        then
        shift
    fi
elif [ "$1" = "-v" ] #verbose mode
    then
    VERBOSE=true
    shift
    if [ "$1" = "-q" ] #can't be both, so we ignore it
        then
        shift
    fi
fi

if [ $# = 0 ]
    then
    $0 --help
    exit
fi

URL=${2-$DEFAULT_URL} #if second argument is empty set URL to default URL

case $1 in
    0 ) REQUEST="OKAY";;
    1 ) REQUEST="WARNING";;
    2 ) REQUEST="CRITICAL";;
    * ) echo "Error: Illegal status"; $0 --help; exit;;
esac

if [ $VERBOSE ]
    then
    echo "------ REQUEST -------"
    echo "Sending status: $REQUEST"
    echo "to: $URL"
fi

$COMMAND $URL status=$REQUEST > /tmp/status_out

if ! ( [ $QUIET ] || [ $VERBOSE ] ) #if neither quiet nor verbose, i.e. normal operation
    then
    head -n 1 /tmp/status_out #output only the HTTP status code
fi

if [ $VERBOSE ]
    then
    echo "------ RESPONSE ------"
    cat /tmp/status_out
    echo
fi
