#!/bin/sh

#CONFIG
DEFAULT_URL="http://httpbin.org/put "
COMMAND="./send_status"

if [ "$1" = "--help" ] #show help and exit
    then
    echo "Usage: $0 [OPTION] [-t TIME] [URL]"
    echo "  OPTION:"
    echo "      -v: verbose"
    echo "      -q: quiet"
    echo " -t TIME: length of time to wait between changing statuses, as used by sleep; defaults to 1m"
    echo "     URL: URL to send statuses to; defaults to $DEFAULT_URL"
    exit
fi

if [ "$1" = "-q" ] #quiet mode
    then
    OPTION="-q"
    shift
    if [ "$1" = "-v" ] #can't be both, so we ignore it
        then
        shift
    fi
elif [ "$1" = "-v" ] #verbose mode
    then
    OPTION="-v"
    shift
    if [ "$1" = "-q" ] #can't be both, so we ignore it
        then
        shift
    fi
fi

if [ "$1" = "-t" ]
    then
    shift
    TIME=$1
    shift
else
    TIME="1m"
fi

URL=${1-$DEFAULT_URL} #if no argument is given, use default URL

while [ true ]
do
    if ! [ $OPTION ]
        then echo -n "WARNING : "
    fi
    $COMMAND $OPTION 1 $URL
    sleep $TIME
    if ! [ $OPTION ]
        then echo -n "CRITICAL: "
    fi
    $COMMAND $OPTION 2 $URL
    sleep $TIME
    if ! [ $OPTION ]
        then echo -n "OKAY    : "
    fi
    $COMMAND $OPTION 0 $URL
    sleep $TIME
done
